[package]
name = "windows-gaming"
version = "0.1.0"
authors = ["main() <main@ehvag.de>"]

[dependencies]
nix = "0.7.0"
xdg = "^2.1"
log = "0.3.8"
env_logger = "0.4.3"
time = "0.1.37"
clap = "2.26"
common = { path = "common" }
driver = { path = "driver" }
wizard = { path = "wizard" }
