[package]
name = "driver"
version = "0.1.0"
authors = ["main() <main@ehvag.de>"]

[dependencies]
libc = "0.2"
lazy_static = "0.2"
nix = "0.7.0"
users = "0.5.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
libudev = "0.2.0"
itertools = "0.6"
log = "0.3.8"
mio = "0.6"
bytes = "0.4"
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
tokio-uds = "0.1"
tokio-timer = "0.1"
tokio-process = "0.1"
tokio-signal = "0.1"
dbus = "0.5"
input = "0.2.1"
xcb = "0.8.1"
prost = { git = "https://github.com/danburkert/prost.git" }
clientpipe-proto = { path = "clientpipe-proto" }
common = { path = "../common" }
