[package]
name = "windows-gaming-driver"
version = "0.1.0"
authors = ["main() <main@ehvag.de>"]

[dependencies]
libc = "0.2"
lazy_static = "0.2"
nix = { version = "0.7.0", features = ["signalfd"] }
users = "0.5.2"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7"
timerfd = "0.2.0"
libudev = "0.2.0"
num_cpus = "1.2.0"
xdg = "^2.1"
itertools = "0.6"
byteorder = "1.0"
