[package]
name = "clientpipe-proto"
version = "0.1.0"
authors = ["main() <main@ehvag.de>"]
edition = "2018"

[dependencies]
prost = "0.9.0"
bytes = "1.1.0"

[build-dependencies]
prost-build = "0.9.0"
